# -*- coding: utf-8 -*-
"""CODE.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1usG8WF5GaSmvCBbRlG5-oFZfpjm9NlIo
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
# Load differential gene expression results
data = pd.read_csv("DEG_results.csv")

# Calculate -log10 adjusted p-value
data["-log10_padj"] = -np.log10(data["padj"])
# Define significantly differentially expressed genes
data["Significant"] = (
    (abs(data["log2FoldChange"]) > 1) &
    (data["padj"] < 0.05)
)
# Set publication-quality figure parameters
plt.rcParams.update({
    "font.size": 12,
    "figure.dpi": 300,
    "axes.linewidth": 1.2
})
# Generate volcano plot
plt.figure(figsize = (8, 6))
plt.scatter (
    data["log2FoldChange"],
    data["-log10_padj"],
    c=data["Significant"],
    alpha=0.7
)
# Add significance thresholds
plt.axvline(x=1, linestyle="--")
plt.axvline(x=-1, linestyle="--")
plt.axhline(y=-np.log10(0.05), linestyle="--")
plt.xlabel("Log2 Fold Change")
plt.ylabel("-Log10 Adjusted P-value")
plt.title("Differential Gene Expression Following Exercise")
plt.tight_layout()
# Save publication-quality figure
plt.savefig(
    "volcano_plot.svg",
    format="svg",
    bbox_inches="tight"
)
plt.show()